name: CD
run-name: ${{ github.actor }}
on:
  pull_request:
    types: [closed]
    branches:
      - main
env:
  IMAGE_TAG: leandroinf23/elchat:${{github.sha}}
jobs:
  build-deploy:
    runs-on:
      labels: [self-hosted, linux, x64, lsc]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME_LSC }}
          password: ${{ secrets.DOCKERHUB_TOKEN_LSC }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{env.IMAGE_TAG}}

      - name: Check and Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
        id: install

      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_CAU }}

      - name: Replace and Apply Kubernetes Manifests
        uses: swdotcom/update-and-apply-kubernetes-configs@v1
        with:
          k8-config-file-paths: |
            .k8s/namespace.yml
            .k8s/elChat/deployment.yml
            .k8s/elChat/service.yml
            .k8s/elChat/ingress.yml
          replacement-method: defined
      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_LSC }}

      - name: Replace and Apply Kubernetes Manifests
        uses: swdotcom/update-and-apply-kubernetes-configs@v1
        with:
          k8-config-file-paths: |
            .k8s/namespace_schultze.yml
            .k8s/schultze/deployment.yml
            .k8s/schultze/service.yml
            .k8s/schultze/ingress.yml
          replacement-method: defined
